### ISSUE TITLE
IP's not showing in terminal, no output file as well

### ISSUE THREAD

**Issue by lajostkm** [vincentcox/bypass-firewalls-by-DNS-history#3]
I'm not sure if this is a bug or my own mistake. I tried this on Parrot OS with jq installed.
Tried both commands on three different domains, to find out if there is an equal address from those three domains. Unfortunately results are not as expected:

No bypass found;
Neither creates output file (this should?)

My input as follows...
$ bash waf.sh -d DOMAIN.BLA -o output
$ bash waf.sh -d DOMAIN.BLA -o /media/user/data/Scripts/wafbypass/output.txt

Output from terminal...
[-] 3 Domains collected...
[-] Scraping IP's from (sub)domains (100%)
[-] 24 IP's gathered from DNS history...
[-] Launching requests to origin servers...
[-] Waiting on replies from origin servers...
[-] No Bypass found!

$ locate output
returns nothing...
$ locate output.txt
returns nothing...

$ cd /media/user/data/Scripts/wafbypass/
$ ls
LICENSE  README.md  waf.sh

**Comment by vincentcox** [comment]
Hi there!
Sorry for the late reply: holiday and OSCP preparations. 
About your issue: It is indeed possible that a WAF bypass is **not** found.

The `-o` flag defines where the file with the IP's will be written, **if a Waf Bypass is found**.

In case of no finding, there will be no output file. And that is what happened in this situation. 

If you really want to dig further on the WAF bypass I recommend reading https://github.com/0xInfection/Awesome-WAF

Good luck and happy hunting!
