### ISSUE TITLE
nothing comes up

### ISSUE THREAD

**Issue by RuneFTP** [vincentcox/bypass-firewalls-by-DNS-history#6]
![Screenshot_5](https://user-images.githubusercontent.com/54816528/73851546-f5a23d00-482d-11ea-820d-d63d8c179f98.png)
This is all im getting there's no ip or anything 
and this is exactly what i pasted 
"bash bypass-firewalls-by-DNS-history.sh -d example.com"
any help or something im doing wrong? thanks!

**Comment by vincentcox** [comment]
Hi there, thanks for your report!
Are you using mac?

**Comment by RuneFTP** [comment]
Im using MobaXterm to connect to my VPS from a RDP windows 10 XD
![Screenshot_6](https://user-images.githubusercontent.com/54816528/73851865-85e08200-482e-11ea-8539-6fc11fb20755.png)

**Comment by vincentcox** [comment]
Ok great, I'll investigate!

**Comment by RuneFTP** [comment]
Okie! thanks for fast reply :D

**Comment by vincentcox** [comment]
Seems an issue with a call to https://dnsdumpster.com/. If you go to that site, and fill in a site, you'll see that it keeps loading. Mayby they have server issues.
For the rest, the tool is working (takes a bit more time).

![image](https://user-images.githubusercontent.com/9286611/73857313-086d3f80-4837-11ea-8b0f-b8a38f9c595b.png)

![image](https://user-images.githubusercontent.com/9286611/73857341-14f19800-4837-11ea-9468-f04d45a353cb.png)

Do you have the latest version? And does your error also happens with "example.com"? Because the screenshots you provided are drawn on to censor another domain.

**Comment by RuneFTP** [comment]
![E905914F-EDF6-48FC-B9C6-9ACABDC8386D](https://user-images.githubusercontent.com/54816528/73858435-ad3c4c80-4838-11ea-9b6b-926b13ab1cbf.jpeg)
I seem to be getting this red error that u don’t 
cat: /tmp/waf-bypass-output-example.com.txt: No such file or directory
And like I said this is what I am pasting 
bash bypass-firewalls-by-DNS-history.sh -d example.com

**Comment by vincentcox** [comment]
Are you sure you are using the latest version?

Try ‘git pull’ to get the latest version. If you have the same error with the new version I made a mistake in my latest commit. Let me know if you face the same error. 

Thanks!

>

**Comment by RuneFTP** [comment]
![56EB4C4E-43C2-4BFA-AD9F-887841E5AD01](https://user-images.githubusercontent.com/54816528/73859391-415ae380-483a-11ea-9481-50d00f2bf1c4.jpeg)

**Comment by RuneFTP** [comment]
Were u able to find a fix or is it on my end?

**Comment by h0nus** [comment]
Same error/problem found!

![image](https://user-images.githubusercontent.com/23401728/74087781-e4f10180-4a8f-11ea-93b5-e7c9259e2070.png)

**Comment by vincentcox** [comment]
Hi all,

Can you try this version of the script and let me know if it works now?

[bypass-firewalls-by-DNS-history.sh.zip](https://github.com/vincentcox/bypass-firewalls-by-DNS-history/files/4180725/bypass-firewalls-by-DNS-history.sh.zip)

Sorry for the delay, I was not home this weekend!

**Comment by RuneFTP** [comment]
i guess it works? this time it says no bypasses found lol
![image](https://user-images.githubusercontent.com/54816528/74160343-8a85ab80-4c1d-11ea-95d1-8bc6c4c9249c.png)

**Comment by vincentcox** [comment]
Yeah I ran some tests on sites I know the bypass works and it gives the correct results. Glad to hear that the error message is gone!

If something is still wrong, or you have questions, feel free to open a new one!

I posted a fix: https://github.com/vincentcox/bypass-firewalls-by-DNS-history/commit/d77d389013bcedabcd38f15f6e22c1e382281d0a.

You can `git pull` again to get the latest version.
