### ISSUE TITLE
Bash Syntax error

### ISSUE THREAD

**Issue by adik69** [vincentcox/bypass-firewalls-by-DNS-history#7]
bypass-firewalls-by-DNS-history.sh: 13: bypass-firewalls-by-DNS-history.sh: Syntax error: "(" unexpected

Jq is installed on the sytem

**Comment by vincentcox** [comment]
Hi there,
Can you say on what system you have this issue? Mac/linux/..?

**Comment by vincentcox** [comment]
Hi there, 
I am closing this issue because there was no response. Feel free to submit a comment even if it's closed.
